default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nikola_workshops_dev

test:
  <<: *default
  database: nikola_workshops_test

production:
  <<: *default
  database: nikola_workshops_production
